todo/lists/urls.py
from django.urls import path
from .views import *

app_name = 'lists'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('create', ListCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ListDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ListUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ListDeleteView.as_view(), name='delete'),
    path('<int:list_pk>/task/create', TaskCreateView.as_view(), name='task-create'),
    path('<int:list_pk>/task/update/<int:pk>', TaskUpdateView.as_view(), name='task-update'),
    path('<int:list_pk>/task/delete/<int:pk>', TaskDeleteView.as_view(), name='task-delete'),

]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lists/', include('lists.urls', namespace='lists')),
]

todo/lists/models.py
from django.db import models


class List(models.Model):
    title = models.CharField(max_length=32)
    description = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)




class Task(models.Model):
    task = models.CharField(max_length=150)
    due_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)


    todo_list = models.ForeignKey('lists.List',
                            on_delete=models.CASCADE,
                            related_name='tasks')

    class Meta:
        ordering = ['-due_date']

todo/lists/forms.py
from django import forms
from django.forms.models import ModelForm
from .models import List, Task

class ListForm(ModelForm):
    class Meta:
        model = List
        fields = ['title', 'description']

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['task', 'due_date']

todo/lists/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic.detail import DetailView


from .models import Task, List
from .forms import TaskForm, ListForm



class HomePageView(View):
    template_name = 'lists/home.html'

    def get(self, request, *args, **kwargs):
        lists = List.objects.all()

        return render(request, self.template_name, {'lists':lists})


class ListDetailView(DetailView):
    model = List
    template_name = 'lists/detail.html'


class ListUpdateView(View):
    form_class = ListForm
    template_name = 'lists/update.html'

    def get(self, request, *args, **kwargs):
        model = List.objects.get(pk=self.kwargs['pk'])
        form = self.form_class(instance=model)

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        model = List.objects.get(pk=self.kwargs['pk'])
        form = self.form_class(request.POST, instance=model)
        if form.is_valid():
            form.save()
            return redirect('lists:detail', pk=model.pk)

        return render(request, self.template_name, {'form': form})



class ListDeleteView(View):
    def post(self,request, *args, **kwargs):
        model = List.objects.get(pk=self.kwargs['pk'])
        if request.method =='POST':
            model.delete()
            return redirect('lists:home')



class ListCreateView(View):
    form_class = ListForm
    template_name = 'lists/create.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            model = form.save()
            return redirect('lists:detail', pk=model.pk)

        return render(request, self.template_name, {'form': form})




class TaskDeleteView(View):
    def post(self,request, *args, **kwargs):
        model = Task.objects.get(pk=self.kwargs['pk'])
        model.delete()
        return redirect('lists:detail', pk=self.kwargs['list_pk'])

class TaskCreateView(View):
    form_class = TaskForm
    template_name = 'lists/tasks/create.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        lists = List.objects.get(pk=self.kwargs['list_pk'])

        return render(request, self.template_name, {'form': form})



    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        todo_list = List.objects.get(pk=self.kwargs['list_pk'])
        if form.is_valid():
            model = form.save(commit=False)
            model.todo_list = todo_list
            model.save()
            return redirect('lists:detail', pk=todo_list.pk)

        return render(request, self.template_name, {'form': form})

class TaskUpdateView(View):
    def post(self, request, *args, **kwargs):
        model = Task.objects.get(pk=self.kwargs['pk'])
        model.completed = not model.completed
        model.save()
        return redirect('lists:detail', pk=self.kwargs['list_pk'])

templates/layout.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}To Do | Home{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/site.css' %}">
  {% block stylesheets %}{% endblock %}
</head>
<body>
  <h1>My Todo List!</h1>
  <div id="navigation">
    <ul>
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'lists:lists' %}">Lists</a></li>
    </ul>
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="{% static 'js/site.js' %}"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

todo/templates/layout.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}To Do | Home{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/site.css' %}">
  {% block stylesheets %}{% endblock %}
</head>
<body>
  <h1>My Todo List!</h1>
  <div id="navigation">
    <ul>
      <li><a href="{% url 'lists:home' %}">Home</a></li>
    </ul>
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="{% static 'js/site.js' %}"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

todo/templates/lists/create.html
{% extends "layout.html" %}
{% load static %}

{% block title %} My ToDo | Create List {% endblock %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create!</button>
  </form>

{% endblock %}

todo/templates/lists/home.html
{% extends "layout.html" %}
{% load static %}
{% block title %}My ToDo | Home{% endblock %}

{% block content %}
<h1>Hello!</h1>
<div>
  <p>
    <a href="{% url 'lists:create' %}"><button>Create A List!</button></a>
  </p>
    <div id="lists">
      {% for list in lists %}
        <h3>
          <a href="{% url 'lists:detail' pk=list.pk %}">{{ list.title }}</a>
          <form method="POST" action="{% url 'lists:delete' pk=list.pk  %}">
            {% csrf_token %}
            <button>Delete</button>
          </form>
        </h3>
      {% empty %}
        <p>
          You have no Lists!
        </p>
        {% endfor %}
    </div>
  </div>
{% endblock %}

todo/templates/lists/tasks/create.html
{% extends "layout.html" %}
{% load static %}
{% block title %} My ToDo | Create Task {% endblock %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create!</button>
  </form>

{% endblock %}

todo/templates/lists/update.html
{% extends "layout.html" %}
{% load static %}

{% block title %} My ToDo | Update List {% endblock %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Update!</button>
  </form>

{% endblock %}